<html>
<head>
  <title>Reg&iacute;strate</title>
  <link rel="stylesheet" href="estilo.css">
</head>
<body>
  <form action="regitro.phtml" method="post" class="formulario">
    <input type="submit" value="Registrar">
  <?php
  include("registro.phtml");
  ?>
  </form>
  <form action="regitro.phtml" method="post" class="formulario">
    <input type="submit" value="Iniciar-Secci&oacute;n">
  <?php
 

 
  ?>
  </form>
</body>
</html>
    