<html>

	<head>
		<title>Regístrate</title>
        <link rel="stylesheet" href="estilo.css">
	</head>

	<body>

		<form action="regitro.phtml" method="get" class="formulario">
			<input type="submit" value="Registrar">
		</form>
        <form action="regitro.phtml" method="get" class="formulario">
            <input type="submit" value="Iniciar-Secci&oacute;n">
		</form>
	
	</body>

</html>
       
    