<html>

	<head>
		<title>Regístrate</title>
	</head>

	<body>

		<form action="seccion-registro.php" method="get">
            Nombres<input type="text" name="nombre"><br>
            Apellidos<input type="text" name="Apellidos"><br>
			Correo <input type="text" name="Correo "><br>
            Contraseña <input type="text" name="Correo "><br>
			<input type="submit" value="Registrar">

		</form>
	
	</body>

</html>